language: python
cache: pip

os:
  - linux

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

jobs:
  include:
    - python: 3.8
      env: TOX_ENV=flake8
    - python: 3.8
      env: TOX_ENV=docs

install:
  - pip install tox-travis coveralls

script:
  # if custom env specified, use it else just use current environment parameters
  - if [ -n "${TOX_ENV}" ]; then
      tox -e $TOX_ENV;
    else
      tox;
    fi

after_success:
  - coveralls

deploy:
  # deploys to PyPI on any tagged commit
  - provider: pypi
    username: "__token__"
    password:
      secure: g9uYWatkFcV3NPtuycrKX+oGGSgYvls3s6LlQmrvTC3cENojplc+8NcSITNSpDoQlov9H2kTQ5sfb2zb65Rthv41X9aP/DboZSnubcOUZfnXvwjtKqAv3RrmHhAe9mdGL4oPo1NRm+ixWle7rRIbyKHZAfs6FzsTAiRTzzDOoaYdwR0ag17Nj7t4M1w3tzBbM6Huf7yXC4QJjZk+8Pq6FDjFMfc7U/RC2hP2xMCJKZr31c9+NGc7y+a90G7y7/4bdgTN5z1lxBR1cN9/prmfHrqDMycGraARb6MLnb5XccSLbnLD/OB+RlfF0CJNSnbulot97VYxFWTzOiDu4mKQCHQtcR01RzwJtvwEsrrNZeMYhWygnSoMPvu6uyGUjGmgfdeXbcCnFKxWUNc7qPQ1xg5+F2JKf10oVuNMyqTfw9ZdSzvTDdor1aooHl7KYHtAhFrSD6+JWuBCPUhZvYHmwMANsjUQF2ogoznaJGV025SauaXwwLSOQHhLzpOYin38Ocg4Cp2ZeLvjzI228emzeQ6Ox7HXlEYJTRp7vf1r/aQj7qbMoq5Rcd4OrTtX6uGxYT4A8T3ivSN5iTR8+F7T8UEG5pW9Cxb7miX4igK/l281n7AcPcXPNSlhPvdjfyuL2Y1jXU386eY/l2RqCVHCf1PNm2zS+HmCKKSacCX+hKI=
    edge: true # opt in to dpl v2
    distributions: sdist bdist_wheel
    on:
      tags: true
      repo: AmadeusITGroup/AutoSSL
    # Upload artifacts only once
    skip_existing: true
