name: Python package

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
  push:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, pypy3]
        TOX_OPTS: ['']
        include:
          - python: 3.9
            TOX_OPTS: -e flake8
          - python: 3.9
            TOX_OPTS: -e docs

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions coveralls
      # if custom env specified, use it else just use current environment parameters
      - name: Test with Tox
        run: tox ${{matrix.TOX_OPTS}}
      # Not using coverallsapp/github-action@master as it requires lcov output not supported by pytest
      # Possible solutions:
      # - Use github action AndreMiras/coveralls-python-action@develop
      #   https://github.com/marketplace/actions/coveralls-python
      # - Convert .coverage to lcov.info using coveragepy-lcov (requiring python>=3.8)
      #   https://github.com/coverallsapp/github-action/issues/30#issuecomment-878741378
      # - Calling coversalls directly
      #   https://github.com/coverallsapp/github-action/issues/30#issuecomment-791094512
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

